# Generated by Django 5.1.1 on 2024-09-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
